"""
corpus_gen.py
Reproducible synthetic corpus generator for the Compliance-Constrained Semantic
Fingerprinting (CCSF) proof-of-concept simulation.

Three groups are produced over a shared set of eight ANDS policy topics:
  (1) ORGANIC  - simulated organic human discourse (heterogeneous stance, register,
                 length; slang, typos, fragments, emoji).
  (2) SYNTH    - compliance-constrained coordinated synthetic advocacy. Generated by
                 a "talking-point engine": a small set of core propositions, each
                 rendered through paraphrase/synonym variation so that surface forms
                 differ (low lexical overlap) while meaning converges. Sentence length
                 is controlled, stance is held constant per account, and a
                 compliance lexicon is woven in. This operationalises "coordinated
                 originality": non-duplicative text that is semantically aligned.
  (3) PROF     - legitimate professional / civil-society public-health advocacy
                 (human-written style). Disciplined and formal, with some
                 policy vocabulary, BUT topically broad and stance-diverse. This is a
                 SPECIFICITY control: a hard negative that shares some surface
                 properties (low burstiness, formal register) with SYNTH without being
                 coordinated synthetic advocacy.

All randomness is seeded. The generator is the documented data-generating process for
the simulation; it is NOT a claim about real-world prevalence.
"""
import random
import numpy as np

SEED = 20260604
random.seed(SEED)
np.random.seed(SEED)

TOPICS = ["age_restrictions", "advertising_regulation", "flavour_restrictions",
          "retail_licensing", "taxation", "youth_exposure",
          "harm_reduction_framing", "enforcement_policy"]

# ----------------------------------------------------------------------------------
# COMPLIANCE LEXICON (transparent, pre-registered list; used by both the SYNTH engine
# and, independently, by the feature extractor). Presence is not itself suspicious.
# ----------------------------------------------------------------------------------
COMPLIANCE_LEXICON = [
    "harm reduction", "adult choice", "adult consumers", "consumer freedom",
    "smoke-free alternatives", "smoke-free", "balanced regulation",
    "proportionate regulation", "evidence-based policy", "evidence-based",
    "innovation", "personal responsibility", "less harmful", "reduced-risk",
    "responsible regulation", "informed choice", "freedom to choose",
]

# ==================================================================================
# (1) ORGANIC HUMAN DISCOURSE
# ==================================================================================
ORG_OPENERS = ["honestly", "ngl", "tbh", "ok so", "lol", "wait", "idk", "look",
               "real talk", "fwiw", "imo", "yeah", "nah", "hmm", "see"]
ORG_PRO_RESTRICTION = [
    "kids are getting hooked on these things at my school and it's scary",
    "flavours like bubblegum are obviously aimed at teenagers come on",
    "my nephew vapes more than he breathes, ban the sweet ones already",
    "tax them like cigarettes, simple",
    "i've seen 13 yr olds buying these at the corner shop, licensing is a joke",
    "advertising near schools should just be illegal full stop",
    "the disposables are an environmental nightmare too btw",
    "we banned cig ads for a reason, why is this any different",
    "enforcement is non existent round here, shops sell to anyone",
]
ORG_ANTI_RESTRICTION = [
    "vaping got me off a 20-a-day habit after 15 years, leave it alone",
    "flavour bans just push people back to cigarettes, makes no sense",
    "im an adult i can decide what i put in my body thanks",
    "the tax hike means i might as well smoke again, great job",
    "prohibition never works, it just creates a black market",
    "switched 3 years ago and my chest feels so much better",
    "why punish ex smokers for the sins of a few dodgy shops",
    "nanny state nonsense, regulate the cowboys not the rest of us",
]
ORG_PERSONAL = [
    "tried the mango pods, way too sweet for me, went back to mint",
    "my coil keeps burning out anyone else??",
    "battery died at the worst time today ugh",
    "anyone know if the new menthol ones are any good",
    "spent way too much on juice this month lmao",
    "the chemist near me stopped stocking my brand, gutted",
    "vape shop guy was actually really helpful tbf",
    "got a sore throat from a dodgy disposable, never again",
]
ORG_NEUTRAL_MIXED = [
    "i mean both sides have a point? protect kids but dont punish quitters",
    "the science seems messy honestly, depends which study you read",
    "regulation is fine but it has to actually be enforced or whats the point",
    "i switched and it helped me but i wouldnt recommend it to a non smoker",
    "complicated issue, not as black and white as twitter makes out",
    "guess we'll see what the consultation says",
]
ORG_OFFTOPIC = [
    "anyway who's watching the match tonight",
    "this weather is doing my head in",
    "off topic but the new phone update is terrible",
    "need coffee before i can think about any of this",
]
ORG_EMOJI = ["", "", " 😂", " 🙄", " 🤷", " 👀", " 💀", " 🔥", " …", " !!", " ??"]

def _typo(s):
    # occasional human typo / casing noise
    if random.random() < 0.18 and len(s) > 6:
        i = random.randint(1, len(s) - 2)
        s = s[:i] + s[i + 1] + s[i] + s[i + 2:]
    if random.random() < 0.12:
        s = s.replace(" the ", " teh ", 1)
    if random.random() < 0.15:
        s = s.lower()
    return s

# A minority of genuine humans write in a disciplined, formal register and occasionally
# reach for policy vocabulary. These are the realistic FALSE-POSITIVE risks.
ORG_FORMAL = [
    "the regulatory balance here is genuinely difficult to get right",
    "from a public health standpoint the priority should be young people",
    "i do think proportionate rules make more sense than a blanket ban",
    "evidence is mixed and policy should reflect that uncertainty",
    "adult smokers trying to quit shouldn't be an afterthought in this debate",
    "enforcement matters more than the wording of the statute honestly",
]

# GENUINE HUMAN HARM-REDUCTION ADVOCATES: fluent, stance-consistent, and they use the
# exact compliance vocabulary that a synthetic campaign would. They are real people with
# personal stories and idiosyncratic phrasing. These are the HARDEST true negatives and
# the central reason compliance vocabulary alone cannot indicate inauthenticity.
ORG_HR_ADVOCATE = [
    "I quit a 25-year habit with vaping and I genuinely believe in harm reduction for adults",
    "as an ex-smoker I think adult choice has to count for something in this debate",
    "the evidence that switching is less harmful saved my life, full stop",
    "balanced regulation is fine but please don't price ordinary quitters out",
    "we keep talking about kids but where is the voice for adults who finally stopped smoking",
    "I've watched friends go back to cigarettes after flavour bans, it's heartbreaking honestly",
    "smoke-free alternatives worked for me when patches and gum never did",
    "I'm not industry, I'm just someone who quit, and I want evidence-based policy not panic",
    "personal responsibility matters but so does keeping safer options affordable and legal",
    "the innovation in these devices is the only reason I'm not smoking today",
]
ORG_HR_PERSONAL = [
    "my doctor actually suggested I try it and I never looked back",
    "two years smoke free this month and I'm not going back to analogues",
    "started on 18mg now I'm on 3mg, that's progress nobody talks about",
    "the corner shop near me got raided for selling to kids, that's the real problem not me",
]

def make_organic(n_accounts=40, posts_per=5):
    rows = []
    casual_pools = [ORG_PRO_RESTRICTION, ORG_ANTI_RESTRICTION, ORG_PERSONAL,
                    ORG_NEUTRAL_MIXED, ORG_OFFTOPIC]
    casual_w = [0.27, 0.27, 0.22, 0.16, 0.08]
    for a in range(n_accounts):
        acc = f"org_{a:02d}"
        roll = random.random()
        # ~30% genuine fluent harm-reduction advocates (hard negatives),
        # ~15% formal/disciplined humans, rest casual
        kind = "advocate" if roll < 0.30 else ("formal" if roll < 0.45 else "casual")
        consistent = (kind in ("advocate", "formal")) or (random.random() < 0.20)
        fixed_pool = None
        if kind == "casual" and consistent:
            fixed_pool = random.choice([ORG_PRO_RESTRICTION, ORG_ANTI_RESTRICTION])
        for _ in range(posts_per):
            if kind == "advocate":
                n_sent = random.choices([1, 2, 3, 4], weights=[0.18, 0.34, 0.30, 0.18])[0]
            elif kind == "formal":
                n_sent = random.choices([2, 3, 4], weights=[0.4, 0.4, 0.2])[0]
            else:
                n_sent = random.choices([1, 2, 3, 4, 5], weights=[0.30, 0.30, 0.22, 0.12, 0.06])[0]
            sents = []
            for _s in range(n_sent):
                if kind == "advocate":
                    pool = ORG_HR_ADVOCATE if random.random() < 0.7 else ORG_HR_PERSONAL
                    frag = random.choice(pool)
                    if random.random() < 0.35:
                        frag = random.choice(["honestly", "look", "real talk", "imo"]) + " " + frag
                elif kind == "formal":
                    if random.random() < 0.6:
                        frag = random.choice(ORG_FORMAL)
                        if random.random() < 0.25:
                            frag += " " + random.choice(["balanced regulation matters",
                                                         "this is about adult choice too",
                                                         "evidence-based policy please"])
                    else:
                        frag = random.choice(random.choices(casual_pools, weights=casual_w)[0])
                else:
                    if fixed_pool is not None and random.random() < 0.7:
                        frag = random.choice(fixed_pool)
                    else:
                        frag = random.choice(random.choices(casual_pools, weights=casual_w)[0])
                    if random.random() < 0.5:
                        frag = random.choice(ORG_OPENERS) + " " + frag
                emoji = "" if kind in ("formal",) else random.choice(ORG_EMOJI)
                frag = _typo(frag) + emoji
                sents.append(frag.strip())
            text = " ".join(sents)
            rows.append(dict(account=acc, group="organic", topic=random.choice(TOPICS), text=text))
    return rows

# ==================================================================================
# (2) COMPLIANCE-CONSTRAINED SYNTHETIC ADVOCACY  (talking-point engine)
# ==================================================================================
# Core propositions (semantic content). All share one disciplined stance:
# light-touch regulation + "harm reduction" framing. Each proposition has several
# paraphrase realisations so generated posts are NOT textual duplicates.
SYNTH_PROPS = {
    "adults_deserve_access": [
        "adult consumers deserve continued access to less harmful alternatives",
        "responsible adults should retain the freedom to choose smoke-free products",
        "informed adult users ought to keep access to reduced-risk options",
        "grown consumers are entitled to make their own choices about safer products",
    ],
    "balanced_not_bans": [
        "balanced regulation protects young people far better than prohibition",
        "proportionate rules safeguard youth without removing adult options",
        "a measured framework shields minors while preserving adult access",
        "sensible oversight protects children without resorting to outright bans",
    ],
    "evidence_supports": [
        "the evidence base increasingly supports these products as harm reduction tools",
        "a growing body of evidence frames these alternatives as reduced-risk",
        "scientific evidence continues to position these products as less harmful",
        "the data increasingly recognise the harm reduction potential of these options",
    ],
    "bans_backfire": [
        "flavour bans risk pushing former smokers back toward combustible cigarettes",
        "overly strict rules may drive ex-smokers back to far more harmful products",
        "heavy-handed restrictions could reverse the gains made by adult switchers",
        "disproportionate measures threaten to undo progress among adult quitters",
    ],
    "innovation_value": [
        "innovation in this category has helped many adults move away from smoking",
        "product innovation has supported countless adults in leaving cigarettes behind",
        "continued innovation offers adult smokers a credible smoke-free pathway",
        "advances in this sector give adult consumers a viable less harmful route",
    ],
    "enforce_existing": [
        "enforcing existing age verification is more effective than new blanket rules",
        "better enforcement of current age limits beats sweeping new restrictions",
        "applying the rules already on the books works better than fresh prohibitions",
        "stronger enforcement of existing safeguards is preferable to broad new bans",
    ],
    "tax_regressive": [
        "excise hikes fall hardest on lower-income adults trying to quit smoking",
        "punitive taxation penalises the very smokers we want to help switch",
        "raising taxes on safer products simply protects the cigarette trade",
        "regressive taxes on these products undermine public health goals",
    ],
    "smokers_left_behind": [
        "the millions of adults who have already switched are too often ignored",
        "policy debate overlooks the adults who quit smoking using these products",
        "we should not abandon the smokers who finally found something that works",
        "the voices of successful adult switchers are missing from this conversation",
    ],
    "comparative_risk": [
        "international evidence suggests these products are markedly less harmful than smoking",
        "leading reviews place the relative risk well below that of combustible tobacco",
        "the comparative-risk picture clearly favours these products over cigarettes",
        "expert assessments consistently rank these alternatives as far less harmful",
    ],
    "black_market_risk": [
        "prohibition tends to hand the market to unregulated illicit suppliers",
        "bans rarely remove demand; they simply create an unregulated grey market",
        "driving products underground makes them less safe, not more",
        "restrictive policy risks fuelling an uncontrolled illicit trade",
    ],
    "support_quitting": [
        "these products belong in the toolkit for adults who want to stop smoking",
        "for many adults this is the most effective route away from cigarettes",
        "cessation support should include the option that actually works for people",
        "we should make it easier, not harder, for adults to leave smoking behind",
    ],
    "trust_adults": [
        "adults can weigh the risks and make informed decisions for themselves",
        "treating adult consumers as incapable of informed choice is patronising",
        "informed adults do not need the state to decide this for them",
        "respecting adult autonomy is consistent with protecting young people",
    ],
}
SYNTH_CONNECTORS = ["Moreover,", "Importantly,", "At the same time,", "Crucially,",
                    "In practice,", "Ultimately,", "Notably,", "That said,"]
SYNTH_CLOSERS = [
    "Policymakers should pursue evidence-based policy rather than restriction.",
    "A proportionate, evidence-based approach serves public health best.",
    "Responsible regulation, not prohibition, is the proportionate path forward.",
    "Balanced, evidence-based policy protects both adults and young people.",
    "The proportionate response is responsible regulation grounded in evidence.",
]
# short fillers used to inject mild length variation in "looser" campaigns
SYNTH_SHORT = ["This matters.", "It is that simple.", "The point stands.",
               "Worth remembering.", "Let us be clear."]
# light human-edit perturbations (colloquial asides, contractions, mild noise)
HUMAN_EDITS = [" honestly", " tbh", " imo", " - just saying", " (my view)", " fwiw"]

def _light_edit(text, p=0.5):
    if random.random() < p:
        text = text.replace("should ", "should really ", 1)
    if random.random() < p:
        text = text.rstrip(".") + random.choice(HUMAN_EDITS) + "."
    if random.random() < 0.3:
        text = text.replace("regulation", "regulaton", 1)  # typo
    if random.random() < 0.3:
        text = text[0].lower() + text[1:]
    return text

def _render_synth(tightness, prop_subset=None):
    """tightness in [0,1]: 1 = maximally disciplined campaign, 0 = loose.
    prop_subset: the campaign's messaging repertoire (subset of SYNTH_PROPS keys)."""
    prop_keys = prop_subset if prop_subset else list(SYNTH_PROPS.keys())
    k = random.choices([2, 3], weights=[0.55, 0.45])[0]
    k = min(k, len(prop_keys))
    chosen = random.sample(prop_keys, k)
    sents = []
    for j, pk in enumerate(chosen):
        s = random.choice(SYNTH_PROPS[pk])
        s = s[0].upper() + s[1:]
        if j > 0 and random.random() < (0.4 + 0.5 * tightness):
            s = random.choice(SYNTH_CONNECTORS) + " " + s[0].lower() + s[1:]
        sents.append(s + ".")
    if random.random() < (1 - tightness) * 0.6:
        sents.insert(random.randint(0, len(sents)), random.choice(SYNTH_SHORT))
    if random.random() < (0.55 + 0.4 * tightness):
        sents.append(random.choice(SYNTH_CLOSERS))
    return " ".join(sents)

def make_synth(n_accounts=16, posts_per=10):
    rows = []
    all_keys = list(SYNTH_PROPS.keys())
    for a in range(n_accounts):
        acc = f"syn_{a:02d}"
        tightness = random.uniform(0.45, 1.0)
        edit_p = random.uniform(0.0, 0.35)
        subset = random.sample(all_keys, random.randint(6, 9))  # campaign repertoire
        for _ in range(posts_per):
            text = _render_synth(tightness, prop_subset=subset)
            if random.random() < edit_p:
                text = _light_edit(text, p=0.4)
            rows.append(dict(account=acc, group="synthetic", topic=random.choice(TOPICS), text=text))
    return rows

# ==================================================================================
# (4) HUMAN-EDITED SYNTHETIC ("mixed")  -- the hard, realistic semi-automated case
# ==================================================================================
def make_mixed(n_accounts=10, posts_per=8):
    """Synthetic talking points heavily rewritten by a human: colloquial register,
    varied length, typos, occasional emoji, lower compliance density. Designed to
    sit BETWEEN organic and synthetic and to be difficult to detect."""
    rows = []
    for a in range(n_accounts):
        acc = f"mix_{a:02d}"
        for _ in range(posts_per):
            base = _render_synth(tightness=random.uniform(0.3, 0.7))
            # aggressive human editing
            base = _light_edit(base, p=0.8)
            base = _light_edit(base, p=0.6)
            # break into a more human rhythm: drop a connector, add an opener
            base = base.replace("Moreover, ", "").replace("Crucially, ", "")
            if random.random() < 0.6:
                base = random.choice(ORG_OPENERS) + " " + base[0].lower() + base[1:]
            if random.random() < 0.5:
                base = base.rstrip(".") + random.choice(ORG_EMOJI)
            rows.append(dict(account=acc, group="mixed", topic=random.choice(TOPICS), text=base))
    return rows

# ==================================================================================
# (3) LEGITIMATE PROFESSIONAL ADVOCACY  (specificity control, human-written style)
# ==================================================================================
# Disciplined and formal, but genuinely diverse in stance and topic, and authored in
# a recognisably human professional register (varied syntax, organisation-specific
# framing). Spans public-health bodies, clinicians, and an industry-watchdog voice.
PROF_SENTENCES = [
    "Our organisation urges members to respond to the consultation before the deadline this Friday.",
    "Independent review of the latest cohort study suggests the relative-risk picture remains uncertain and warrants caution.",
    "We welcome the proposed point-of-sale display restrictions but note that enforcement funding has not been confirmed.",
    "Frontline cessation services report rising demand from young clients, and we need resourcing to match.",
    "The committee's analysis indicates that excise structure, not headline rate alone, drives substitution behaviour.",
    "We remain concerned about marketing that appears designed to appeal to under-eighteens.",
    "Article 5.3 obligations mean policymakers should document and publish all industry contacts.",
    "Clinicians in our network describe mixed outcomes and call for better-quality longitudinal data.",
    "A licensing scheme with meaningful penalties would close the gap that current voluntary codes leave open.",
    "Our position is that protecting minors and supporting adult quit attempts are not mutually exclusive goals.",
    "We caution against framing that treats commercial messaging as neutral public information.",
    "The disposable-product waste stream raises distinct environmental and equity questions for local authorities.",
    "Survey data from our regional partners show uneven retailer compliance with existing age checks.",
    "We recommend that any flavour policy be paired with a robust monitoring and evaluation plan.",
    "Transparency registers for stakeholder meetings would strengthen public trust in the process.",
    "Members have asked for clearer guidance on how to discuss switching with patients who still smoke.",
    "Our briefing summarises the trial evidence without overstating the strength of individual findings.",
    "We support proportionate taxation provided revenue is ring-fenced for cessation support.",
    "The coalition notes that youth exposure online is poorly captured by current advertising rules.",
    "We will continue to scrutinise third-party groups that do not disclose their funding sources.",
]

def make_prof(n_accounts=12, posts_per=7):
    rows = []
    for a in range(n_accounts):
        acc = f"pro_{a:02d}"
        for _ in range(posts_per):
            n_sent = random.choices([2, 3, 4], weights=[0.45, 0.40, 0.15])[0]
            sents = random.sample(PROF_SENTENCES, n_sent)
            text = " ".join(sents)
            topic = random.choice(TOPICS)
            rows.append(dict(account=acc, group="professional", topic=topic, text=text))
    return rows

def build_corpus():
    rows = make_organic() + make_synth() + make_prof() + make_mixed()
    random.shuffle(rows)
    for i, r in enumerate(rows):
        r["id"] = f"p{i:04d}"
    return rows

if __name__ == "__main__":
    rows = build_corpus()
    import collections
    c = collections.Counter(r["group"] for r in rows)
    print("Total posts:", len(rows))
    print("By group:", dict(c))
    print("Accounts:", len(set(r["account"] for r in rows)))
    for g in ["organic", "synthetic", "professional"]:
        ex = next(r for r in rows if r["group"] == g)
        print(f"\n[{g}] {ex['account']} ({ex['topic']}):\n  {ex['text']}")
