"""Stage 2: independent multi-generator CCSF validation via OpenRouter.

Design (see stage2_config.json):
  * 3 independent generator families (Google Gemini, Alibaba Qwen, ByteDance Seed),
    verified against the live OpenRouter catalogue; a 4th family (Tencent hy3) is used
    ONLY for LLM paraphrase transforms so paraphrase never leaks a generator family
    across leave-one-family-out folds.
  * Per generator: 20 coordinated-campaign accounts, 20 uncoordinated organic-style
    control accounts, 12 vocabulary-matched professional control accounts; 8 posts per
    account, generated in a single request per account.
  * Controls are generated by the SAME model as the coordinated condition, so the
    evaluation measures coordination signal, not generator identity.
  * The professional control deliberately uses commercial-policy framing vocabulary,
    replacing the Stage 1 zero-match control.
  * Automated transformations (LLM paraphrase, seeded noise insertion, seeded sentence
    restructuring) are applied at account level to both coordinated and organic
    accounts so every transformation value contains both classes. No human editing.
  * Full provenance per response: model ID, provider, OpenRouter generation ID,
    timestamps, token usage, raw response, sampling parameters.

Phases:
  python stage2_run.py selftest                      # offline invariant checks
  python stage2_run.py build     --config stage2_config.json
  python stage2_run.py snapshot  --config stage2_config.json   # archive model catalogue
  python stage2_run.py generate  --config stage2_config.json   # calls OpenRouter (costs money)
  python stage2_run.py transform --config stage2_config.json   # paraphrase calls + seeded local transforms
  python stage2_run.py ingest    --config stage2_config.json   # corpus CSV + manifest + holdout splits
  python stage2_run.py features  --config stage2_config.json   # GPT-2 perplexity + MiniLM features
  python stage2_run.py evaluate  --config stage2_config.json   # leave-one-condition-out results
  python stage2_run.py all       --config stage2_config.json

This script never fabricates model text: `generate` writes only actual API responses,
`ingest` refuses accounts without a stored raw response, and `selftest` touches no
corpus files.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import random
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from validation_framework import (REQUIRED_COLUMNS, ProvenanceError, build_all_holdouts,
                                  validate_records, write_dataset_manifest)

HERE = Path(__file__).resolve().parent

# --------------------------------------------------------------------------- utilities

def load_config(path: str | Path) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def load_env(path: Path | None = None) -> dict:
    """Minimal .env parser (KEY=VALUE, ignores comments/blank lines)."""
    env = {}
    path = path or HERE / ".env"
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            env[key.strip()] = value.strip().strip('"').strip("'")
    return env


def out_dir(config: dict) -> Path:
    d = HERE / config.get("outputs_dir", "stage2_outputs")
    d.mkdir(exist_ok=True)
    return d


def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.write_text("".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows), encoding="utf-8")


def read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def utc_now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat()

# --------------------------------------------------------------------------- OpenRouter client

class OpenRouterError(RuntimeError):
    pass


def _api_key(config: dict) -> str:
    import os
    env_name = config["openrouter"].get("api_key_env", "OPENROUTER_API_KEY")
    key = os.environ.get(env_name) or load_env().get(env_name)
    if not key:
        raise OpenRouterError(
            f"{env_name} not found in environment or .env. Add it before running generate/transform.")
    return key


def _http_json(url: str, payload: dict | None, headers: dict, timeout: int) -> dict:
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    req = urllib.request.Request(url, data=data, headers=headers,
                                 method="POST" if payload is not None else "GET")
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def chat_completion(config: dict, model: str, messages: list[dict], temperature: float,
                    provider_preferences: dict | None) -> dict:
    """Call OpenRouter chat completions with retries. Returns the raw response dict."""
    oc = config["openrouter"]
    url = oc["base_url"].rstrip("/") + "/chat/completions"
    headers = {
        "Authorization": f"Bearer {_api_key(config)}",
        "Content-Type": "application/json",
        "X-Title": oc.get("app_title", "CCSF-Stage2"),
    }
    payload: dict = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "top_p": oc.get("top_p", 0.95),
        "max_tokens": oc.get("max_tokens", 1600),
        "response_format": {"type": "json_object"},
    }
    if oc.get("disable_reasoning", True):
        payload["reasoning"] = {"enabled": False}
    if provider_preferences:
        payload["provider"] = provider_preferences
    last_error: Exception | None = None
    for attempt in range(oc.get("max_retries", 3) + 1):
        try:
            response = _http_json(url, payload, headers, oc.get("timeout_seconds", 180))
            if "error" in response:
                raise OpenRouterError(str(response["error"]))
            return response
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", "replace")[:500]
            last_error = OpenRouterError(f"HTTP {exc.code}: {body}")
            # Some providers reject response_format/reasoning: strip and retry once.
            if exc.code == 400:
                payload.pop("response_format", None)
                payload.pop("reasoning", None)
            if exc.code in (401, 402, 403):
                raise last_error
        except Exception as exc:  # network hiccups, JSON errors
            last_error = exc
        time.sleep(min(2 ** attempt * 2, 30))
    raise OpenRouterError(f"Request failed after retries: {last_error}")


def extract_posts(response: dict, expected: int) -> list[str]:
    """Parse {'posts': [...]} out of a chat completion, tolerating fenced JSON."""
    content = response["choices"][0]["message"]["content"] or ""
    text = content.strip()
    fence = re.search(r"```(?:json)?\s*(.*?)```", text, re.S)
    if fence:
        text = fence.group(1).strip()
    try:
        obj = json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start == -1 or end <= start:
            raise ValueError("No JSON object in model output.")
        obj = json.loads(text[start:end + 1])
    posts = obj.get("posts") if isinstance(obj, dict) else obj
    if not isinstance(posts, list):
        raise ValueError("JSON output lacks a 'posts' array.")
    posts = [str(p).strip() for p in posts if str(p).strip()]
    # Truncate if model returns extra posts; error only if insufficient
    if len(posts) > expected:
        posts = posts[:expected]
    if len(posts) < expected:
        raise ValueError(f"Expected {expected} posts, got {len(posts)}.")
    return posts

# --------------------------------------------------------------------------- account plan

ORGANIC_PERSONAS = [
    "a parent of teenagers worried about vaping in schools",
    "an adult who switched from cigarettes to vaping two years ago",
    "a small-town nurse who sees both smokers and vapers",
    "a university student who follows health policy news casually",
    "a corner-shop owner who sells age-restricted products",
    "a runner who quit smoking years ago and dislikes all nicotine",
    "a local journalist who covers council public-health debates",
    "a sceptical retiree who thinks most health claims are overblown",
    "a bartender who watches smoking-area habits change",
    "a public-health student with nuanced, evolving views",
]
ORGANIC_STANCES = ["broadly supportive of these products", "broadly critical of these products",
                   "genuinely ambivalent and undecided"]
PROFESSIONAL_ORGS = [
    "a national public-health charity",
    "a consumer advocacy organisation for adults who use nicotine alternatives",
    "a trade association representing independent nicotine retailers",
]


def build_account_plan(config: dict) -> list[dict]:
    design = config["design"]
    topics = config["topics"]
    families = [f["id"] for f in config["prompt_families"]]
    temps = design["temperatures"]
    transforms = design["transformations_cycle"]
    repertoires = config["campaign_repertoires"]
    plan = []
    for gen in config["generators"]:
        gid = gen["generator_id"]
        for cls, n in (("coordinated", design["accounts_per_generator"]["coordinated"]),
                       ("organic_control", design["accounts_per_generator"]["organic_control"]),
                       ("professional_control", design["accounts_per_generator"]["professional_control"])):
            for k in range(n):
                repertoire = repertoires[k % len(repertoires)] if cls == "coordinated" else None
                if cls == "coordinated":
                    campaign_id = f"{gid}_camp{k % len(repertoires)}"
                    class_label, subtype = "coordinated_synthetic", "coordinated"
                elif cls == "organic_control":
                    campaign_id = f"{gid}_control_organic"
                    class_label, subtype = "simulated_human_control", "organic"
                else:
                    campaign_id = f"{gid}_control_professional"
                    class_label, subtype = "simulated_human_control", "professional"
                transformation = (transforms[k % len(transforms)]
                                  if cls in design["transformations_apply_to"]
                                  else design["professional_control_transformation"])
                plan.append({
                    "account_id": f"{gid}_{subtype}_{k:02d}",
                    "generator_id": gid,
                    "generator_family": gen["generator_family"],
                    "generator_model": gen["model"],
                    "generator_revision": gen["revision"],
                    "class_label": class_label,
                    "control_subtype": subtype,
                    "campaign_id": campaign_id,
                    "topic": topics[k % len(topics)],
                    "prompt_family": families[k % len(families)],
                    "prompt_revision": next(f["revision"] for f in config["prompt_families"]
                                            if f["id"] == families[k % len(families)]),
                    "temperature": temps[k % len(temps)],
                    "transformation_id": transformation,
                    "talking_point_repertoire": repertoire["name"] if repertoire else f"none_{subtype}_voice",
                    "style_instruction": (f"campaign_voice" if cls == "coordinated" else
                                          f"organic_persona_{k % len(ORGANIC_PERSONAS)}" if cls == "organic_control"
                                          else f"professional_org_{k % len(PROFESSIONAL_ORGS)}"),
                    "persona_index": k,
                })
    return plan

# --------------------------------------------------------------------------- prompts

SYSTEM_MESSAGE = (
    "You are generating clearly labelled synthetic research data used to evaluate a public-health "
    "social-media surveillance method. The text will never be published as real posts. "
    "Respond with a single JSON object of the form {\"posts\": [\"...\", \"...\"]} and nothing else."
)


def build_user_prompt(config: dict, account: dict) -> str:
    n = config["design"]["posts_per_account"]
    topic = account["topic"]
    base = (f"Write {n} distinct social-media posts (each roughly 30-80 words) about {topic}. "
            f"The posts are from one account posting over several weeks. ")
    if account["control_subtype"] == "coordinated":
        rep = next(r for r in config["campaign_repertoires"]
                   if r["name"] == account["talking_point_repertoire"])
        points = "; ".join(rep["points"])
        family = account["prompt_family"]
        if family == "direct_talking_points":
            body = (f"This account is part of an advocacy campaign. Campaign objective: {rep['objective']}. "
                    f"Each post should advance one or two of these campaign talking points, in the account's own words: {points}.")
        elif family == "grassroots_persona":
            body = (f"This account presents as an ordinary member of the public but participates in an advocacy campaign. "
                    f"Campaign objective: {rep['objective']}. Weave the campaign's talking points into personal-sounding posts: {points}.")
        else:  # indirect_policy_discussion
            body = (f"This account supports an advocacy campaign but avoids sloganeering. Campaign objective: {rep['objective']}. "
                    f"Discuss the policy topic in an indirect, discussion-style way that still advances these points without repeating their wording: {points}.")
    elif account["control_subtype"] == "organic":
        persona = ORGANIC_PERSONAS[account["persona_index"] % len(ORGANIC_PERSONAS)]
        stance = ORGANIC_STANCES[account["persona_index"] % len(ORGANIC_STANCES)]
        family = account["prompt_family"]
        if family == "direct_talking_points":
            body = (f"This is the personal account of {persona}, {stance}. Give their own varied opinions, "
                    f"reactions and questions; the posts should not follow any campaign or shared message list.")
        elif family == "grassroots_persona":
            body = (f"This is the personal account of {persona}, {stance}. Include everyday context, personal anecdotes "
                    f"and occasional off-topic asides; opinions may shift or contradict slightly across posts.")
        else:
            body = (f"This is the personal account of {persona}, {stance}. The posts react to news items, ask questions "
                    f"and think aloud about the topic rather than pushing a fixed position.")
    else:  # professional
        org = PROFESSIONAL_ORGS[account["persona_index"] % len(PROFESSIONAL_ORGS)]
        terms = ", ".join(config["professional_vocabulary_matching"]["terms_to_use_naturally"])
        body = (f"This is the official account of {org}, run by a communications professional. "
                f"The posts are consistent, sourced and organisationally on-message, and they naturally use standard "
                f"policy terminology such as: {terms}. They are professional advocacy, not a coordinated covert campaign.")
    return base + body + " Return JSON only."

# --------------------------------------------------------------------------- deterministic transforms

def _rng_for(seed: int, account_id: str) -> random.Random:
    return random.Random(f"{seed}:{account_id}")


def noise_insertion(text: str, rng: random.Random) -> str:
    words = text.split(" ")
    for i, w in enumerate(words):
        if len(w) > 4 and rng.random() < 0.04:
            j = rng.randrange(1, len(w) - 2)
            words[i] = w[:j] + w[j + 1] + w[j] + w[j + 2:]
    text = " ".join(words)
    if rng.random() < 0.5:
        text = text.replace(",", "", rng.randrange(1, 3))
    sentences = re.split(r"(?<=[.!?])\s+", text)
    sentences = [s[0].lower() + s[1:] if s and rng.random() < 0.4 else s for s in sentences]
    return " ".join(sentences)


def sentence_restructure(text: str, rng: random.Random) -> str:
    sentences = [s for s in re.split(r"(?<=[.!?])\s+", text.strip()) if s]
    rebuilt = []
    for s in sentences:
        parts = re.split(r",\s+(?:and|but|because|so)\s+", s, maxsplit=1)
        if len(parts) == 2 and rng.random() < 0.7:
            second = parts[1].rstrip(".!?")
            rebuilt.append(second[0].upper() + second[1:] + ". " + parts[0].rstrip(".!?") + ".")
        else:
            rebuilt.append(s)
    if len(rebuilt) > 1 and rng.random() < 0.5:
        rebuilt = rebuilt[::-1]
    return " ".join(rebuilt)


DETERMINISTIC_TRANSFORMS = {"noise_insertion": noise_insertion, "sentence_restructure": sentence_restructure}

# --------------------------------------------------------------------------- phases

def cmd_build(config: dict) -> None:
    plan = build_account_plan(config)
    requests = []
    for account in plan:
        requests.append({
            "request_id": f"gen_{account['account_id']}",
            "phase": "generate",
            "account": account,
            "model": account["generator_model"],
            "temperature": account["temperature"],
            "messages": [{"role": "system", "content": SYSTEM_MESSAGE},
                         {"role": "user", "content": build_user_prompt(config, account)}],
        })
    path = out_dir(config) / "stage2_requests.jsonl"
    write_jsonl(path, requests)
    counts = {}
    for r in plan:
        key = (r["generator_id"], r["control_subtype"])
        counts[key] = counts.get(key, 0) + 1
    print(f"Wrote {len(requests)} account-level generation requests to {path}")
    for (gid, subtype), n in sorted(counts.items()):
        print(f"  {gid:20s} {subtype:12s} {n} accounts x {config['design']['posts_per_account']} posts")


def cmd_snapshot(config: dict) -> None:
    oc = config["openrouter"]
    url = oc["base_url"].rstrip("/") + "/models"
    headers = {"Authorization": f"Bearer {_api_key(config)}"}
    catalogue = _http_json(url, None, headers, oc.get("timeout_seconds", 180))
    stamp = _dt.date.today().isoformat()
    path = out_dir(config) / f"openrouter_models_snapshot_{stamp}.json"
    path.write_text(json.dumps(catalogue, indent=1), encoding="utf-8")
    ids = {m.get("id") for m in catalogue.get("data", [])}
    wanted = [g["model"] for g in config["generators"]] + [config["transform_model"]["model"]]
    missing = [m for m in wanted if m not in ids]
    if missing:
        raise OpenRouterError(f"Configured models missing from live catalogue: {missing}")
    print(f"Catalogue snapshot saved to {path}; all {len(wanted)} configured models present.")


def _run_requests(config: dict, requests: list[dict], responses_path: Path,
                  provider_prefs_for: dict[str, dict | None]) -> None:
    done = {r["request_id"] for r in read_jsonl(responses_path) if r.get("parse_ok")}
    pending = [r for r in requests if r["request_id"] not in done]
    print(f"{len(done)} already complete; {len(pending)} pending.")
    expected = config["design"]["posts_per_account"]
    failures = 0
    with responses_path.open("a", encoding="utf-8") as sink:
        for i, request in enumerate(pending, 1):
            record = {"request_id": request["request_id"], "requested_model": request["model"],
                      "temperature": request["temperature"], "top_p": config["openrouter"].get("top_p", 0.95),
                      "reasoning_disabled": config["openrouter"].get("disable_reasoning", True),
                      "messages": request["messages"], "timestamp_utc": utc_now()}
            try:
                response = chat_completion(config, request["model"], request["messages"],
                                           request["temperature"], provider_prefs_for.get(request["model"]))
                record.update({
                    "openrouter_generation_id": response.get("id"),
                    "returned_model": response.get("model"),
                    "provider": response.get("provider"),
                    "usage": response.get("usage"),
                    "finish_reason": response["choices"][0].get("finish_reason"),
                    "raw_content": response["choices"][0]["message"]["content"],
                })
                posts = extract_posts(response, expected)
                record.update({"parse_ok": True, "posts": posts})
            except Exception as exc:
                record.update({"parse_ok": False, "error": f"{type(exc).__name__}: {exc}"})
                failures += 1
            sink.write(json.dumps(record, ensure_ascii=False) + "\n")
            sink.flush()
            print(f"  [{i}/{len(pending)}] {request['request_id']}: "
                  f"{'ok' if record.get('parse_ok') else 'FAILED - ' + record.get('error', '')[:80]}")
    if failures:
        print(f"{failures} request(s) failed. Re-run this phase to retry only the failures.")
        sys.exit(1)


def cmd_generate(config: dict) -> None:
    requests = read_jsonl(out_dir(config) / "stage2_requests.jsonl")
    if not requests:
        raise SystemExit("Run `build` first.")
    prefs = {g["model"]: g.get("provider_preferences") for g in config["generators"]}
    _run_requests(config, requests, out_dir(config) / "stage2_raw_responses.jsonl", prefs)
    print("Generation complete.")


def cmd_transform(config: dict) -> None:
    responses = {r["request_id"]: r for r in read_jsonl(out_dir(config) / "stage2_raw_responses.jsonl")
                 if r.get("parse_ok")}
    plan = build_account_plan(config)
    seed = config["seed"]
    tm = config["transform_model"]
    paraphrase_requests = []
    for account in plan:
        if account["transformation_id"] != "llm_paraphrase":
            continue
        source = responses.get(f"gen_{account['account_id']}")
        if source is None:
            raise SystemExit(f"Missing generation for {account['account_id']}; finish `generate` first.")
        prompt = ("Paraphrase each of the following posts. Preserve each post's meaning, stance and rough length, "
                  "but change the wording and sentence structure substantially. Return a JSON object "
                  "{\"posts\": [...]} with the paraphrases in the same order.\n\n"
                  + json.dumps({"posts": source["posts"]}, ensure_ascii=False))
        paraphrase_requests.append({
            "request_id": f"para_{account['account_id']}",
            "phase": "transform", "account": account, "model": tm["model"], "temperature": 0.7,
            "messages": [{"role": "system", "content": SYSTEM_MESSAGE},
                         {"role": "user", "content": prompt}],
        })
    if paraphrase_requests:
        _run_requests(config, paraphrase_requests, out_dir(config) / "stage2_paraphrase_responses.jsonl",
                      {tm["model"]: tm.get("provider_preferences")})
    # assemble final per-account post sets
    paraphrased = {r["request_id"]: r for r in read_jsonl(out_dir(config) / "stage2_paraphrase_responses.jsonl")
                   if r.get("parse_ok")}
    final_rows = []
    for account in plan:
        source = responses.get(f"gen_{account['account_id']}")
        if source is None:
            raise SystemExit(f"Missing generation for {account['account_id']}.")
        tid = account["transformation_id"]
        if tid == "none":
            posts, revision = source["posts"], "v1"
        elif tid == "llm_paraphrase":
            para = paraphrased.get(f"para_{account['account_id']}")
            if para is None:
                raise SystemExit(f"Missing paraphrase for {account['account_id']}.")
            posts, revision = para["posts"], f"{tm['model']}@{tm['revision']}"
        else:
            rng = _rng_for(seed, account["account_id"])
            posts = [DETERMINISTIC_TRANSFORMS[tid](p, rng) for p in source["posts"]]
            revision = f"stage2_deterministic_v1_seed{seed}"
        final_rows.append({"account": account, "posts": posts, "transformation_revision": revision})
    write_jsonl(out_dir(config) / "stage2_final_posts.jsonl", final_rows)
    print(f"Wrote final post sets for {len(final_rows)} accounts.")


def cmd_ingest(config: dict) -> None:
    import csv
    rows = read_jsonl(out_dir(config) / "stage2_final_posts.jsonl")
    if not rows:
        raise SystemExit("Run `transform` first (it also assembles untransformed accounts).")
    records = []
    for row in rows:
        account = row["account"]
        for i, text in enumerate(row["posts"]):
            records.append({
                "record_id": f"{account['account_id']}_p{i}",
                "account_id": account["account_id"],
                "campaign_id": account["campaign_id"],
                "class_label": account["class_label"],
                "text": text,
                "topic": account["topic"],
                "generator_id": account["generator_id"],
                "generator_family": account["generator_family"],
                "generator_model": account["generator_model"],
                "generator_revision": account["generator_revision"],
                "prompt_family": account["prompt_family"],
                "prompt_revision": account["prompt_revision"],
                "temperature": str(account["temperature"]),
                "diversity_setting": "high" if account["temperature"] >= 0.7 else "controlled",
                "talking_point_repertoire": account["talking_point_repertoire"],
                "style_instruction": account["style_instruction"],
                "transformation_id": account["transformation_id"],
                "transformation_revision": row["transformation_revision"],
                "evaluation_batch": account["generator_id"],
                "split_role": "evaluation",
                "seed": str(config["seed"]),
            })
    validate_records(records)
    corpus = out_dir(config) / "stage2_validation_corpus.csv"
    with corpus.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=REQUIRED_COLUMNS)
        writer.writeheader()
        writer.writerows(records)
    manifest = write_dataset_manifest(records, out_dir(config) / "stage2_dataset_manifest.json")
    splits = build_all_holdouts(records, out_dir(config) / "stage2_splits")
    print(json.dumps({"corpus": str(corpus), "summary": manifest, "split_manifests": splits}, indent=2))


def cmd_features(config: dict) -> None:
    import csv
    import math
    import numpy as np
    import torch
    from transformers import GPT2TokenizerFast, GPT2LMHeadModel
    from sentence_transformers import SentenceTransformer
    from corpus_gen import COMMERCIAL_POLICY_FRAMING_LEXICON

    corpus = out_dir(config) / "stage2_validation_corpus.csv"
    with corpus.open(encoding="utf-8", newline="") as handle:
        records = list(csv.DictReader(handle))
    if not records:
        raise SystemExit("Run `ingest` first.")

    sent_split = re.compile(r"(?<=[.!?])\s+")
    word = re.compile(r"[A-Za-z']+")

    def sentences(t):
        parts = [s.strip() for s in sent_split.split(t.strip()) if s.strip()]
        return parts if parts else [t.strip()]

    def tokens(t):
        return word.findall(t.lower())

    print("Loading GPT-2 and all-MiniLM-L6-v2 (same fixed instruments as Stage 1) ...")
    tok = GPT2TokenizerFast.from_pretrained(config["feature_models"]["perplexity"]["model_id"])
    lm = GPT2LMHeadModel.from_pretrained(config["feature_models"]["perplexity"]["model_id"]).eval()
    emb_model = SentenceTransformer(config["feature_models"]["embedding"]["model_id"])

    def perplexity(text):
        ids = tok(text, return_tensors="pt", truncation=True, max_length=256).input_ids
        if ids.shape[1] < 2:
            ids = tok(text + " .", return_tensors="pt").input_ids
        with torch.no_grad():
            loss = lm(ids, labels=ids).loss.item()
        return math.exp(loss)

    def framing_density(text):
        low = text.lower()
        n_tokens = max(len(tokens(text)), 1)
        hits = 0
        for term in COMMERCIAL_POLICY_FRAMING_LEXICON:
            hits += len(re.findall(r"(?<![a-z])" + re.escape(term.lower()) + r"(?![a-z])", low))
        return hits / n_tokens

    texts = [r["text"] for r in records]
    embeddings = emb_model.encode(texts, normalize_embeddings=True, show_progress_bar=True)
    by_account: dict[str, list[int]] = {}
    for i, r in enumerate(records):
        by_account.setdefault(r["account_id"], []).append(i)

    feature_rows = []
    for account_id, idx in sorted(by_account.items()):
        posts = [records[i] for i in idx]
        ppls = [perplexity(records[i]["text"]) for i in idx]
        all_sentence_lengths = [len(tokens(s)) for i in idx for s in sentences(records[i]["text"])]
        lengths = np.asarray(all_sentence_lengths, float)
        burstiness = float(lengths.std(ddof=0) / lengths.mean()) if lengths.mean() > 0 and len(lengths) > 1 else 0.0
        vectors = np.vstack([embeddings[i] for i in idx])
        if len(vectors) > 1:
            sim = vectors @ vectors.T
            iu = np.triu_indices(len(vectors), k=1)
            convergence = float(sim[iu].mean())
        else:
            convergence = 0.0
        first = posts[0]
        feature_rows.append({
            "account_id": account_id,
            "class_label": first["class_label"],
            "campaign_id": first["campaign_id"],
            "generator_id": first["generator_id"],
            "generator_family": first["generator_family"],
            "prompt_family": first["prompt_family"],
            "topic": first["topic"],
            "transformation_id": first["transformation_id"],
            "temperature": first["temperature"],
            "n_posts": len(idx),
            "ppl_mean": float(np.mean(ppls)),
            "ppl_var": float(np.var(ppls)),
            "burstiness": burstiness,
            "commercial_policy_framing": float(np.mean([framing_density(records[i]["text"]) for i in idx])),
            "convergence": convergence,
        })
    path = out_dir(config) / "stage2_account_features.csv"
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(feature_rows[0].keys()))
        writer.writeheader()
        writer.writerows(feature_rows)
    print(f"Wrote {len(feature_rows)} account-level feature rows to {path}")


def cmd_evaluate(config: dict) -> None:
    import csv
    import numpy as np
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import average_precision_score, roc_auc_score
    from sklearn.pipeline import make_pipeline
    from sklearn.preprocessing import StandardScaler
    from validation_evaluation import FEATURE_COLUMNS, evaluate

    features_csv = out_dir(config) / "stage2_account_features.csv"
    results = {"generated_utc": utc_now(), "feature_columns": list(FEATURE_COLUMNS), "holdouts": {}}
    for field in config["required_holdouts"]:
        manifest = out_dir(config) / "stage2_splits" / f"leave_one_{field}_out.json"
        output = out_dir(config) / f"stage2_eval_leave_one_{field}_out.json"
        results["holdouts"][field] = evaluate(features_csv, manifest, output)

    # extended per-subgroup breakdown for the decisive leave-one-generator-family-out design
    with features_csv.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    families = sorted({r["generator_family"] for r in rows})

    def subtype(row):
        if row["class_label"] == "coordinated_synthetic":
            return "coordinated"
        return "professional" if row["campaign_id"].endswith("_control_professional") else "organic"

    def auc_subset(model, subset):
        y = np.array([r["class_label"] == "coordinated_synthetic" for r in subset], dtype=int)
        if len(np.unique(y)) != 2:
            return None
        x = np.array([[float(r[c]) for c in FEATURE_COLUMNS] for r in subset])
        p = model.predict_proba(x)[:, 1]
        return {"n": len(subset), "roc_auc": float(roc_auc_score(y, p)),
                "pr_auc": float(average_precision_score(y, p))}

    breakdown = []
    for held_out in families:
        train = [r for r in rows if r["generator_family"] != held_out]
        test = [r for r in rows if r["generator_family"] == held_out]
        model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000, class_weight="balanced"))
        x_train = np.array([[float(r[c]) for c in FEATURE_COLUMNS] for r in train])
        y_train = np.array([r["class_label"] == "coordinated_synthetic" for r in train], dtype=int)
        model.fit(x_train, y_train)
        entry = {"held_out_family": held_out,
                 "overall": auc_subset(model, test),
                 "coordinated_vs_organic_only": auc_subset(model, [r for r in test if subtype(r) != "professional"]),
                 "coordinated_vs_professional_only": auc_subset(model, [r for r in test if subtype(r) != "organic"]),
                 "by_transformation": {}}
        for tid in sorted({r["transformation_id"] for r in test}):
            subset = [r for r in test if r["transformation_id"] == tid]
            entry["by_transformation"][tid] = auc_subset(model, subset)
        breakdown.append(entry)
    results["leave_one_family_out_breakdown"] = breakdown

    # token usage summary
    usage = {}
    for name in ("stage2_raw_responses.jsonl", "stage2_paraphrase_responses.jsonl"):
        for r in read_jsonl(out_dir(config) / name):
            if not r.get("parse_ok"):
                continue
            u = r.get("usage") or {}
            model = r.get("returned_model") or r.get("requested_model")
            slot = usage.setdefault(model, {"requests": 0, "prompt_tokens": 0, "completion_tokens": 0})
            slot["requests"] += 1
            slot["prompt_tokens"] += int(u.get("prompt_tokens") or 0)
            slot["completion_tokens"] += int(u.get("completion_tokens") or 0)
    results["token_usage"] = usage

    path = out_dir(config) / "stage2_results.json"
    path.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {path}")
    for entry in breakdown:
        overall = entry["overall"] or {}
        print(f"  held-out {entry['held_out_family']:16s} ROC AUC {overall.get('roc_auc')}")


def cmd_selftest(config: dict) -> None:
    """Offline invariant checks. Touches no corpus files and calls no API."""
    plan = build_account_plan(config)
    n_expected = sum(config["design"]["accounts_per_generator"].values()) * len(config["generators"])
    assert len(plan) == n_expected, (len(plan), n_expected)
    assert len({a["account_id"] for a in plan}) == len(plan)
    # every holdout value must contain both classes (framework requirement)
    for field in config["required_holdouts"]:
        values = {}
        for a in plan:
            values.setdefault(a[field], set()).add(a["class_label"])
        bad = {v for v, labels in values.items() if len(labels) != 2}
        assert not bad, f"holdout {field}: single-class values {bad}"
    # prompts: coordinated prompts must not mention CCSF signal words
    banned = ("perplexity", "burstiness", "embedding", "convergence", "sentence length")
    for a in plan:
        prompt = build_user_prompt(config, a).lower()
        assert not any(b in prompt for b in banned), f"CCSF signal leaked into prompt for {a['account_id']}"
    # professional prompts must include vocabulary-matching terms
    for a in plan:
        if a["control_subtype"] == "professional":
            prompt = build_user_prompt(config, a)
            assert "harm reduction" in prompt and "evidence-based policy" in prompt
    # parser robustness
    fake = {"choices": [{"message": {"content": "```json\n{\"posts\": [\"a\", \"b\"]}\n```"}}]}
    assert extract_posts(fake, 2) == ["a", "b"]
    fake2 = {"choices": [{"message": {"content": "noise {\"posts\": [\"x\", \"y\", \"z\"]} trailing"}}]}
    assert extract_posts(fake2, 3) == ["x", "y", "z"]
    # deterministic transforms reproducible
    sample = "This is a longer example sentence, and it continues with more words here. Short one."
    for name, fn in DETERMINISTIC_TRANSFORMS.items():
        a = fn(sample, _rng_for(config["seed"], "acct"))
        b = fn(sample, _rng_for(config["seed"], "acct"))
        assert a == b, f"{name} not reproducible"
        assert a != sample, f"{name} changed nothing"
    # schema compliance of the ingest mapping (in-memory only, discarded)
    dummy = []
    for account in plan[:8]:
        dummy.append({c: "x" for c in REQUIRED_COLUMNS} | {
            "record_id": f"selftest_{account['account_id']}", "account_id": account["account_id"],
            "class_label": account["class_label"], "text": "selftest placeholder never persisted"})
    try:
        validate_records(dummy)
    except ProvenanceError as exc:
        raise AssertionError(f"ingest mapping violates schema: {exc}")
    print(f"selftest OK: {len(plan)} planned accounts, all holdout values two-class, "
          f"prompts clean, parser and transforms verified.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Stage 2 independent multi-generator CCSF validation.")
    parser.add_argument("phase", choices=["selftest", "build", "snapshot", "generate", "transform",
                                          "ingest", "features", "evaluate", "all"])
    parser.add_argument("--config", default="stage2_config.json")
    args = parser.parse_args()
    config = load_config(args.config)
    phases = {"selftest": cmd_selftest, "build": cmd_build, "snapshot": cmd_snapshot,
              "generate": cmd_generate, "transform": cmd_transform, "ingest": cmd_ingest,
              "features": cmd_features, "evaluate": cmd_evaluate}
    if args.phase == "all":
        for name in ("selftest", "build", "snapshot", "generate", "transform", "ingest", "features", "evaluate"):
            print(f"=== {name} ===")
            phases[name](config)
    else:
        phases[args.phase](config)


if __name__ == "__main__":
    main()
