"""Provenance-first corpus ingestion and holdout split builder for CCSF validation.

This module deliberately does not fabricate model outputs. It supports two routes:
(1) ingest outputs generated by independently configured models, or (2) execute a
user-configured adapter after credentials and model revisions are supplied. The
baseline template simulation is not an independent generator and is never mixed
with this validation corpus.
"""
from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterable

REQUIRED_COLUMNS = (
    "record_id", "account_id", "campaign_id", "class_label", "text", "topic",
    "generator_id", "generator_family", "generator_model", "generator_revision",
    "prompt_family", "prompt_revision", "temperature", "diversity_setting",
    "talking_point_repertoire", "style_instruction", "transformation_id",
    "transformation_revision", "evaluation_batch", "split_role", "seed",
)
VALID_CLASS_LABELS = {"coordinated_synthetic", "simulated_human_control"}
HOLDOUT_FIELDS = ("generator_id", "prompt_family", "topic", "transformation_id")


class ProvenanceError(ValueError):
    """Raised when a corpus cannot support the claimed evaluation."""


@dataclass(frozen=True)
class CorpusRecord:
    record_id: str
    account_id: str
    campaign_id: str
    class_label: str
    text: str
    topic: str
    generator_id: str
    generator_family: str
    generator_model: str
    generator_revision: str
    prompt_family: str
    prompt_revision: str
    temperature: str
    diversity_setting: str
    talking_point_repertoire: str
    style_instruction: str
    transformation_id: str
    transformation_revision: str
    evaluation_batch: str
    split_role: str
    seed: str


def read_records(path: str | Path) -> list[dict[str, str]]:
    with Path(path).open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def validate_records(records: Iterable[dict[str, str]]) -> dict:
    records = list(records)
    if not records:
        raise ProvenanceError("Validation corpus is empty.")
    missing = sorted({c for row in records for c in REQUIRED_COLUMNS if not row.get(c, "").strip()})
    if missing:
        raise ProvenanceError(f"Missing required provenance values: {', '.join(missing)}")
    bad = sorted({r["class_label"] for r in records} - VALID_CLASS_LABELS)
    if bad:
        raise ProvenanceError(f"Unsupported class_label values: {bad}")
    ids = [r["record_id"] for r in records]
    if len(ids) != len(set(ids)):
        raise ProvenanceError("record_id values must be unique.")
    accounts = {r["account_id"] for r in records}
    if len(accounts) < 4:
        raise ProvenanceError("At least four accounts are required for account-level evaluation.")
    by_account = {}
    for row in records:
        by_account.setdefault(row["account_id"], set()).add(row["class_label"])
    mixed_labels = sorted(a for a, labels in by_account.items() if len(labels) != 1)
    if mixed_labels:
        raise ProvenanceError("Each account must have exactly one class_label.")
    return {
        "n_records": len(records),
        "n_accounts": len(accounts),
        "records_by_class": dict(Counter(r["class_label"] for r in records)),
        "accounts_by_class": dict(Counter(next(iter(labels)) for labels in by_account.values())),
        "generators": sorted({r["generator_id"] for r in records}),
        "prompt_families": sorted({r["prompt_family"] for r in records}),
        "topics": sorted({r["topic"] for r in records}),
        "transformations": sorted({r["transformation_id"] for r in records}),
    }


def write_dataset_manifest(records: Iterable[dict[str, str]], output: str | Path) -> dict:
    records = list(records)
    summary = validate_records(records)
    summary["provenance_contract"] = list(REQUIRED_COLUMNS)
    summary["interpretation"] = (
        "Independent-validation corpus. Results are reportable only after every model "
        "and transformation represented here has actually been executed and retained."
    )
    Path(output).write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    return summary


def account_metadata(records: Iterable[dict[str, str]]) -> list[dict[str, str]]:
    """Return one provenance row per account and reject inconsistent account metadata."""
    first: dict[str, dict[str, str]] = {}
    stable = ("class_label", "campaign_id", "generator_id", "generator_family",
              "generator_model", "generator_revision", "prompt_family", "topic",
              "transformation_id", "evaluation_batch", "split_role")
    for row in records:
        account = row["account_id"]
        if account not in first:
            first[account] = {key: row[key] for key in stable} | {"account_id": account}
        else:
            for key in stable:
                if first[account][key] != row[key]:
                    raise ProvenanceError(f"Account {account!r} has inconsistent {key!r}.")
    return list(first.values())


def build_leave_one_condition_out(records: Iterable[dict[str, str]], field: str) -> dict:
    """Build disjoint account-level train/test manifests for one provenance field."""
    if field not in HOLDOUT_FIELDS:
        raise ProvenanceError(f"Unsupported holdout field {field!r}; choose from {HOLDOUT_FIELDS}.")
    accounts = account_metadata(records)
    values = sorted({row[field] for row in accounts})
    if len(values) < 2:
        raise ProvenanceError(f"Need at least two {field} values for a leave-one-out split.")
    splits = []
    for held_out in values:
        test = [r["account_id"] for r in accounts if r[field] == held_out]
        train = [r["account_id"] for r in accounts if r[field] != held_out]
        labels = {r["class_label"] for r in accounts if r["account_id"] in test}
        if labels != VALID_CLASS_LABELS:
            raise ProvenanceError(
                f"Held-out {field}={held_out!r} lacks both classes. Assign matched comparison-control "
                "accounts to each evaluation batch/condition before evaluation."
            )
        splits.append({"holdout_field": field, "held_out_value": held_out,
                       "train_account_ids": train, "test_account_ids": test})
    return {"unit": "account", "field": field, "splits": splits}


def build_all_holdouts(records: Iterable[dict[str, str]], output_dir: str | Path) -> dict[str, str]:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    written = {}
    for field in HOLDOUT_FIELDS:
        manifest = build_leave_one_condition_out(records, field)
        path = output / f"leave_one_{field}_out.json"
        path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        written[field] = str(path)
    return written


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate CCSF independent-validation provenance and build holdouts.")
    parser.add_argument("corpus", help="CSV conforming to validation_corpus_schema.csv")
    parser.add_argument("--manifest", default="validation_dataset_manifest.json")
    parser.add_argument("--split-dir", default="validation_splits")
    args = parser.parse_args()
    records = read_records(args.corpus)
    summary = write_dataset_manifest(records, args.manifest)
    written = build_all_holdouts(records, args.split_dir)
    print(json.dumps({"summary": summary, "split_manifests": written}, indent=2))


if __name__ == "__main__":
    main()
